include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore
    dead_code: warning
    missing_return: error
    dead_null_aware_expression: warning

formatter:
  line_length: 100
  trailing_commas: preserve
